### ISSUE TITLE
wrong freeswitch node name...

### ISSUE THREAD

**Issue by krull** [sip-li/docker-monsterui#1]
@joeblackwaslike great docker work!

Just want to report, on `docker-compose up`, I am seeing this in the console:

```
---8<---
monsterui         |  - - [24/Feb/2017:08:53:50 +0000] "GET / HTTP/1.1" 200 558 "-" "curl/7.38.0"rt=0.000
couchdb           | [notice] 2017-02-24T08:53:53.230179Z couchdb@couchdb.local <0.22317.0> 48f2dcea97 couchdb.local:5984 172.19.0.7 admin GET / 200 ok 2
kazoo             | 08:53:55.415 [info] attempting to connect default freeswitch node 'freeswitch@kazoo.local'
couchdb           | [notice] 2017-02-24T08:53:58.233519Z couchdb@couchdb.local <0.22317.0> 80ee4ca976 couchdb.local:5984 172.19.0.7 admin GET / 200 ok 1
kazoo             | 08:54:00.418 [info] attempting to connect default freeswitch node 'freeswitch@kazoo.local'
couchdb           | [notice] 2017-02-24T08:54:02.271625Z couchdb@couchdb.local <0.29554.0> 6d78060f0e localhost:5984 127.0.0.1 undefined GET /_users 200 ok 1
couchdb           | [notice] 2017-02-24T08:54:03.237325Z couchdb@couchdb.local <0.22317.0> eed64d1c8f couchdb.local:5984 172.19.0.7 admin GET / 200 ok 2
kazoo             | 08:54:05.419 [info] attempting to connect default freeswitch node 'freeswitch@kazoo.local'
--->8---
```

fixed it via:
```
docker exec kazoo sup ecallmgr_maintenance add_fs_node freeswitch@freeswitch.local
```

Cheers.

**Comment by joeblackwaslike** [comment]
Thanks for the kind words @krull

yes this is known but hardly an issue, it's just the way kazoo works.

kazoo itself is set to look for a freeswitch server by default on the same hostname unless configured otherwise.  Your fix is exactly what should be done.

I have some scripts that automate this process locally and on kubernetes.

https://github.com/sip-li/docker-kazoo/tree/master/scripts

clone that repo side by side with the others, run `do-local` with no arguments and you'll see all the commands, as well as an all that will bootstrap the entire thing ready to go.

For instance to do what you just did you can use
```bash
./do-local add-fs-node
```

Closing this issue though since it's not really an issue :)
